# 1. WHAT IS A VARIABLE?

# A variable is a container used to store data in memory.
# It holds a value that can be changed during program execution.


age = 21
name = "Balaji"
print("Name:", name)

# 2. WHAT IS A KEYWORD?

# A keyword is a reserved word in Python that has a special meaning and cannot be used as a variable name.

# 👉 Examples:
# if, else, for, while, def, class, return, True, False

# ❌ Invalid:

# if = 10   # Error

# 🔹 3. PYTHON DATA TYPES

# Data types define the type of data a variable can store.

# Data Type	Description	Example
# int	Integer numbers	10, -5
# float	Decimal numbers	3.14
# str	Text	"Python"
# bool	True / False	True
# list	Ordered, mutable	[1, 2, 3]
# tuple	Ordered, immutable	(1, 2, 3)
# set	Unordered, unique	{1, 2, 3}
# dict	Key–value pairs	{"name": "Balaji"}
# 🔹 4. ADD, SUBTRACT, MULTIPLY, DIVIDE TWO NUMBERS

# (Using input() function)

# # Get input from user
# num1 = int(input("Enter first number: "))
# num2 = int(input("Enter second number: "))

# # Operations
# addition = num1 + num2
# subtraction = num1 - num2
# multiplication = num1 * num2
# division = num1 / num2

# # Output
# print("Addition:", addition)
# print("Subtraction:", subtraction)
# print("Multiplication:", multiplication)
# print("Division:", division)